name: Python Workflow

on:
  push:
  pull_request:

jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Check version
        run: python3 tests/version.py
